language: objective-c
install:
  - brew remove --force xctool
  - brew install xctool --HEAD

script:
  - xcodebuild -workspace refuge-ios/refuge-ios.xcworkspace -scheme refuge-ios -sdk iphonesimulator11.3

